/**
 * Generates the Manual content for the Starlight site: one markdown page per
 * module (from `src/modules/<name>/README.md`), per core primitive (from
 * `src/<name>.md`) and per hand-authored page (from `website/manual/**`).
 * Starlight owns the layout, sidebar, search and syntax highlighting from there.
 *
 * The source `.md` files are the single source — nothing is copied by hand, and
 * no frontmatter is added to them. Guide links are rewritten because they are
 * written for readers *inside* the repo, not for the published site; authored
 * pages are written for the site and are published verbatim.
 *
 * Pure: this module writes nothing. The CLI wrapper (`manual.gen.ts`) writes the
 * files; the test (`manual.test.ts`) asserts the same output.
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(import.meta.url), '../..');
const MODULE_DIR = join(ROOT, 'src/modules');
const SRC_DIR = join(ROOT, 'src');
const AUTHORED_DIR = join(ROOT, 'website/manual');

/**
 * Sidebar position for a hand-authored page, keyed by its path under
 * `website/manual/`. Starlight sorts an autogenerated group by `sidebar.order`
 * and puts every unnumbered page after those, alphabetically, so a group's
 * reading order is stated here rather than inherited from its file names.
 */
const AUTHORED_ORDER: Record<string, number> = {};
const REPO_URL = 'https://github.com/Pierre-Demessence/Entity-Cornponent-System-Engine';
const SUMMARY_MAX = 160;

/**
 * Core-primitive guides, co-located with their source in `src/<name>.md` and
 * published as the Manual's **Core** group. The value is the import line shown
 * at the top of each page; most map to a `@pierre/ecs/<name>` subpath export.
 */
const CORE_GUIDES: Record<string, string> = {
  'component-store': 'Import from `@pierre/ecs/component-store`.',
  'event-bus': 'Import from `@pierre/ecs/event-bus`.',
  'query': 'Import from `@pierre/ecs/query`.',
  'scheduler': 'Import from `@pierre/ecs/scheduler`.',
  'spatial-structure': 'Import from `@pierre/ecs/spatial-structure`.',
  'template': 'Import from `@pierre/ecs/template`.',
  'tick': 'Import from `@pierre/ecs/tick-source` and `@pierre/ecs/tick-runner`.',
  'world': 'Import from `@pierre/ecs/world`.',
};

export interface ManualPage {
  markdown: string;
  /** Path relative to Starlight's content directory, e.g. `manual/math.md`. */
  outPath: string;
}

/** A published guide: a module README or a core-primitive deep-dive. */
type GuideGroup = 'core' | 'modules';

interface Guide {
  name: string;
  group: GuideGroup;
  /** The `Import from …` line rendered above the guide body. */
  importLine: string;
  markdown: string;
  /** The source `.md` file, used as the base for resolving its links. */
  sourcePath: string;
}

/** Context a page's links resolve against: its group plus the known guide names. */
interface LinkContext {
  coreNames: Set<string>;
  group: GuideGroup;
  moduleNames: Set<string>;
}

/** Plain code-unit ordering, so the page order is byte-stable across machines. */
function byName(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function listModuleGuides(): Guide[] {
  return readdirSync(MODULE_DIR, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort(byName)
    .flatMap((name) => {
      const readmePath = join(MODULE_DIR, name, 'README.md');
      if (!existsSync(readmePath))
        return [];
      return [{
        name,
        group: 'modules' as const,
        importLine: `Import from \`@pierre/ecs/modules/${name}\`.`,
        markdown: readFileSync(readmePath, 'utf8'),
        sourcePath: readmePath,
      }];
    });
}

/** The core-primitive guides, read from `src/<name>.md` in a stable order. */
function listCoreGuides(): Guide[] {
  return Object.keys(CORE_GUIDES)
    .sort(byName)
    .flatMap((name) => {
      const sourcePath = join(SRC_DIR, `${name}.md`);
      if (!existsSync(sourcePath))
        return [];
      return [{
        name,
        group: 'core' as const,
        importLine: CORE_GUIDES[name],
        markdown: readFileSync(sourcePath, 'utf8'),
        sourcePath,
      }];
    });
}

/**
 * Module directories that ship without a README, so the build can say so rather
 * than silently publishing an incomplete Manual.
 */
export function modulesWithoutReadme(): string[] {
  return readdirSync(MODULE_DIR, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .filter(name => !existsSync(join(MODULE_DIR, name, 'README.md')))
    .sort(byName);
}

/**
 * The README's first paragraph, flattened to one line for the sidebar and meta
 * description. Markup is unwrapped rather than deleted: a blanket strip of `*`
 * and `_` mangles real text such as `A\* pathfinding` or `bevy_pathfinding`.
 */
export function summaryOf(markdown: string): string {
  const body = markdown.replace(/^#.*$/m, '').trim();
  const paragraph = body.split(/\n\s*\n/).find(chunk => !chunk.startsWith('#'));
  if (!paragraph)
    return '';
  const flat = paragraph
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/\\(.)/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
  if (flat.length <= SUMMARY_MAX)
    return flat;
  const head = flat.slice(0, SUMMARY_MAX);
  const lastSpace = head.lastIndexOf(' ');
  return `${(lastSpace > 0 ? head.slice(0, lastSpace) : head).trimEnd()}...`;
}

function githubUrl(absolutePath: string): string {
  const rel = relative(ROOT, absolutePath).split(sep).join('/');
  const kind = statSync(absolutePath).isDirectory() ? 'tree' : 'blob';
  return `${REPO_URL}/${kind}/main/${rel}`;
}

/** Site route to a guide page, relative to a page in `fromGroup`. */
function routeTo(fromGroup: GuideGroup, group: GuideGroup, name: string): string {
  return fromGroup === group ? `../${name}/` : `../../${group}/${name}/`;
}

/**
 * Rewrites one in-repo link target for the published site. Returns `null` when
 * the link must be dropped (internal docs), otherwise the replacement target.
 *
 * Links are classified by what they resolve to: a core guide (`src/<name>.md`)
 * or module README routes to that guide's page; anything under `docs/` is
 * internal and dropped; source files and examples point at GitHub.
 */
function resolveLink(target: string, fromDir: string, ctx: LinkContext): string | null {
  if (/^(?:[a-z][a-z0-9+.-]*:|\/|#)/i.test(target))
    return target;

  // Matched on shape, not on resolution: some READMEs overshoot the repo root by
  // a level, so an unresolvable `docs/` path must still be dropped rather than
  // published as a dead link.
  if (/(?:^|\/)docs\//.test(target))
    return null;

  const absolute = resolve(fromDir, target);
  const rel = relative(ROOT, absolute).split(sep).join('/');

  const core = /^src\/([^/]+)\.md$/.exec(rel);
  if (core && ctx.coreNames.has(core[1]))
    return routeTo(ctx.group, 'core', core[1]);

  const mod = /^src\/modules\/([^/]+)\/README\.md$/.exec(rel);
  if (mod && ctx.moduleNames.has(mod[1]))
    return routeTo(ctx.group, 'modules', mod[1]);

  if (rel.startsWith('..'))
    return target;

  if (rel.split('/')[0] === 'docs')
    return null;

  return existsSync(absolute) ? githubUrl(absolute) : target;
}

/**
 * Rewrites links outside fenced code blocks only — the READMEs contain code
 * samples with bracketed syntax that must survive verbatim.
 */
function rewriteLinks(markdown: string, sourcePath: string, ctx: LinkContext): string {
  const fromDir = join(sourcePath, '..');
  const linkPattern = /(?<!!)\[([^\]]+)\]\(([^)\s]+)\)/g;
  let inFence = false;

  return markdown
    .split('\n')
    .map((line) => {
      if (/^\s*(?:```|~~~)/.test(line)) {
        inFence = !inFence;
        return line;
      }
      if (inFence)
        return line;
      return line.replace(linkPattern, (_match, text: string, target: string) => {
        const resolved = resolveLink(target, fromDir, ctx);
        return resolved === null ? text : `[${text}](${resolved})`;
      });
    })
    .join('\n');
}

/** Drop the README's own `# Title`; Starlight renders the frontmatter title instead. */
function bodyOf(markdown: string): string {
  const lines = markdown.split('\n');
  const first = lines.findIndex(line => line.trim() !== '');
  if (first !== -1 && lines[first].startsWith('#'))
    lines.splice(first, 1);
  return lines.join('\n').trim();
}

/** The page-level sidebar overrides the generator emits into frontmatter. */
interface SidebarFrontmatter {
  /** Keep the page out of the sidebar while still publishing its route. */
  hidden?: boolean;
  /** Position within its autogenerated group. */
  order?: number;
}

/**
 * YAML frontmatter, with the description quoted so prose punctuation is inert.
 */
function frontmatter(title: string, description: string, sidebar: SidebarFrontmatter = {}): string {
  const quoted = (value: string): string =>
    `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  const lines = [
    sidebar.hidden ? '  hidden: true' : '',
    sidebar.order === undefined ? '' : `  order: ${sidebar.order}`,
  ].filter(line => line !== '');
  const block = lines.length > 0 ? `sidebar:\n${lines.join('\n')}\n` : '';
  return `---\ntitle: ${quoted(title)}\ndescription: ${quoted(description)}\n${block}---\n\n`;
}

/**
 * The section landing page. It is the one authored page that is not a guide:
 * Starlight renders `Overview` from frontmatter, and the manual sidebar injects
 * the link to it, so it carries no heading of its own and stays out of the
 * autogenerated groups.
 */
const LANDING_PAGE = 'index.md';

/** Every `.md` under `dir`, as `/`-joined paths relative to it, in byte-stable order. */
function listMarkdown(dir: string): string[] {
  if (!existsSync(dir))
    return [];
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory())
      found.push(...listMarkdown(join(dir, entry.name)).map(rel => `${entry.name}/${rel}`));
    else if (entry.name.endsWith('.md'))
      found.push(entry.name);
  }
  return found.sort(byName);
}

/**
 * Index of the page's title line: its first `# ` heading that is not inside a
 * fenced block, so a sample opening with a comment (`# install …`) is not
 * mistaken for the title. Exactly one `#` counts, so `## Sub` stays a section.
 * The index, rather than the text, is what callers use to drop the line — the
 * same heading text can appear earlier inside a fence.
 */
function titleLineIndex(lines: readonly string[]): number {
  let inFence = false;
  for (const [index, line] of lines.entries()) {
    if (/^\s*(?:```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (!inFence && /^#[ \t]+\S/.test(line))
      return index;
  }
  return -1;
}

/**
 * Hand-authored Manual pages, read from `website/manual/` and published to the
 * same path under `manual/`. This tree is the only site source outside the
 * generator, and it exists so that a page which is not a guide can be committed
 * rather than hand-placed in `manual/`, which the CLI wipes before writing.
 *
 * A page's title is its first `# ` heading, which is dropped from the body
 * because Starlight renders the frontmatter title as the page heading. Pages
 * link to published routes (`./core/world/`), so nothing rewrites them.
 */
export function renderAuthoredPages(
  dir: string,
  order: Record<string, number> = AUTHORED_ORDER,
): ManualPage[] {
  return listMarkdown(dir).map((rel) => {
    const source = readFileSync(join(dir, rel), 'utf8').trim();
    const outPath = `manual/${rel}`;

    if (rel === LANDING_PAGE) {
      const description = summaryOf(source) || 'How the Manual is organised.';
      return {
        markdown: `${frontmatter('Overview', description, { hidden: true })}${source}\n`,
        outPath,
      };
    }

    const lines = source.split('\n');
    const titleAt = titleLineIndex(lines);
    const title = titleAt === -1
      ? basename(rel, '.md')
      : lines[titleAt].replace(/^#[ \t]+/, '').trim();
    const description = summaryOf(source) || `Manual page ${title}.`;
    // Only the title line is dropped: removing the first line instead would let
    // a page whose prose opens before its heading render the title twice.
    const body = titleAt === -1
      ? source
      : [...lines.slice(0, titleAt), ...lines.slice(titleAt + 1)].join('\n').trim();
    return { markdown: `${frontmatter(title, description, { order: order[rel] })}${body}\n`, outPath };
  });
}

/** Build every Manual page, ready to be written into the Starlight content directory. */
export function renderManualPages(): ManualPage[] {
  const coreGuides = listCoreGuides();
  const moduleGuides = listModuleGuides();
  const coreNames = new Set(coreGuides.map(guide => guide.name));
  const moduleNames = new Set(moduleGuides.map(guide => guide.name));

  const render = (guide: Guide): ManualPage => {
    const description = summaryOf(guide.markdown) || `Guide for ${guide.name}.`;
    const ctx: LinkContext = { coreNames, group: guide.group, moduleNames };
    const body = rewriteLinks(bodyOf(guide.markdown), guide.sourcePath, ctx);
    const intro = `${guide.importLine}\n\n`;
    return {
      markdown: `${frontmatter(guide.name, description)}${intro}${body}\n`,
      outPath: `manual/${guide.group}/${guide.name}.md`,
    };
  };

  return [
    ...renderAuthoredPages(AUTHORED_DIR),
    ...coreGuides.map(render),
    ...moduleGuides.map(render),
  ];
}
